version: '3.3'

services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: zkan/simplezat:stable
    ports:
      - "8000:8000"
    command: ./entrypoint.dev.sh

volumes:
  postgres-data:
