version: "3.3"

services:
  nginx:
    image: zkan/simplezat-nginx:live
    ports:
      - "80:80"
    volumes:
      - app-staticfiles:/app/static
    depends_on:
      - app

  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: zkan/simplezat:live
    volumes:
      - app-staticfiles:/app/static
    command: ./entrypoint.production.sh
    depends_on:
      - db

volumes:
  postgres-data:
  app-staticfiles:
