# Generated by Django 2.1.4 on 2018-12-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
