version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev

  static_analysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Static Analysis
          command: |
            pipenv run --dev flake8

  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: |
            cd simplezat
            pipenv run python manage.py test

  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Development Server
          command: |
            cd deployment
            pipenv install
            pipenv run ansible-playbook -i server_hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat"

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_analysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
